// <auto-generated />
using System;
using D_DStore.DataAccess.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace D_DStore.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("D_DStore.Domain.Entities.BaseProduct.Brand.BrandData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("D_DStore.Domain.Entities.BaseProduct.Brand.CountryData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("D_DStore.Domain.Entities.BaseProduct.ProductImageData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("D_DStore.Domain.Entities.Liquid.FlavorData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Flavors");
                });

            modelBuilder.Entity("D_DStore.Domain.Entities.Product.ProductData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("integer");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("LikeCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("D_DStore.Domain.Enums.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("D_DStore.Domain.Enums.ProductTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("LiquidFlavors", b =>
                {
                    b.Property<int>("FlavorsId")
                        .HasColumnType("integer");

                    b.Property<int>("LiquidsId")
                        .HasColumnType("integer");

                    b.HasKey("FlavorsId", "LiquidsId");

                    b.HasIndex("LiquidsId");

                    b.ToTable("LiquidFlavors");
                });

            modelBuilder.Entity("ProductTags", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("integer");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("ProductsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ProductTags");
                });

            modelBuilder.Entity("D_DStore.Domain.Entities.Consumable.ConsumableData", b =>
                {
                    b.HasBaseType("D_DStore.Domain.Entities.Product.ProductData");

                    b.ToTable("Consumables", (string)null);
                });

            modelBuilder.Entity("D_DStore.Domain.Entities.Liquid.LiquidData", b =>
                {
                    b.HasBaseType("D_DStore.Domain.Entities.Product.ProductData");

                    b.Property<int>("IceLevel")
                        .HasColumnType("integer");

                    b.Property<int>("Nicotine")
                        .HasColumnType("integer");

                    b.Property<int>("Volume")
                        .HasColumnType("integer");

                    b.ToTable("Liquids", (string)null);
                });

            modelBuilder.Entity("D_DStore.Domain.Entities.Vape.VapeData", b =>
                {
                    b.HasBaseType("D_DStore.Domain.Entities.Product.ProductData");

                    b.Property<int>("BatteryCapacity")
                        .HasColumnType("integer");

                    b.Property<decimal>("CoilResistance")
                        .HasColumnType("numeric");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxPower")
                        .HasColumnType("integer");

                    b.Property<decimal>("TankCapacity")
                        .HasColumnType("numeric");

                    b.ToTable("Vapes", (string)null);
                });

            modelBuilder.Entity("D_DStore.Domain.Entities.BaseProduct.Brand.BrandData", b =>
                {
                    b.HasOne("D_DStore.Domain.Entities.BaseProduct.Brand.CountryData", "Country")
                        .WithMany("Brands")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Country");
                });

            modelBuilder.Entity("D_DStore.Domain.Entities.BaseProduct.ProductImageData", b =>
                {
                    b.HasOne("D_DStore.Domain.Entities.Product.ProductData", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("D_DStore.Domain.Entities.Product.ProductData", b =>
                {
                    b.HasOne("D_DStore.Domain.Entities.BaseProduct.Brand.BrandData", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("D_DStore.Domain.Enums.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LiquidFlavors", b =>
                {
                    b.HasOne("D_DStore.Domain.Entities.Liquid.FlavorData", null)
                        .WithMany()
                        .HasForeignKey("FlavorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("D_DStore.Domain.Entities.Liquid.LiquidData", null)
                        .WithMany()
                        .HasForeignKey("LiquidsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductTags", b =>
                {
                    b.HasOne("D_DStore.Domain.Entities.Product.ProductData", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("D_DStore.Domain.Enums.ProductTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("D_DStore.Domain.Entities.Consumable.ConsumableData", b =>
                {
                    b.HasOne("D_DStore.Domain.Entities.Product.ProductData", null)
                        .WithOne()
                        .HasForeignKey("D_DStore.Domain.Entities.Consumable.ConsumableData", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("D_DStore.Domain.Entities.Liquid.LiquidData", b =>
                {
                    b.HasOne("D_DStore.Domain.Entities.Product.ProductData", null)
                        .WithOne()
                        .HasForeignKey("D_DStore.Domain.Entities.Liquid.LiquidData", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("D_DStore.Domain.Entities.Vape.VapeData", b =>
                {
                    b.HasOne("D_DStore.Domain.Entities.Product.ProductData", null)
                        .WithOne()
                        .HasForeignKey("D_DStore.Domain.Entities.Vape.VapeData", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("D_DStore.Domain.Entities.BaseProduct.Brand.BrandData", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("D_DStore.Domain.Entities.BaseProduct.Brand.CountryData", b =>
                {
                    b.Navigation("Brands");
                });

            modelBuilder.Entity("D_DStore.Domain.Entities.Product.ProductData", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("D_DStore.Domain.Enums.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
