services:
  db-products:
    image: postgres:16
    container_name: DDLiquid_Main_DB
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=main_db
    ports:
      - "5432:5432"
    volumes:
      - main_data:/var/lib/postgresql/data
    networks:
      - dotnet_network
volumes:
  main_data:
networks:
  dotnet_network:
    driver: bridge